[build]
  base = "project/"
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Force HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true

# Handle SPA routing - this must be the last redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Enable Netlify's Visual Editor
[build.environment]
  NETLIFY_VISUAL_EDITING = "true"
  NODE_VERSION = "16"
  # Add polyfills for crypto
  NODE_OPTIONS = "--openssl-legacy-provider"

[[headers]]
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=0, s-maxage=31536000, must-revalidate"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Headers to allow Netlify's Visual Editor
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/assets/*"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
